name: Build and deploy Python project to Azure Function App - pdf-expenses-parser

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './PdfParserFunction'
  PYTHON_VERSION: '3.11'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: 📦 Install dependencies into function folder
          run: |
            pip install -r requirements.txt --target=PdfParserFunction/.python_packages/lib/site-packages

      - name: 🔐 Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_61ECBCEEE2C349B28E390F3F4AFA7715 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_347A1FDBB5784101977D1884720AC1B2 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A386F8FEB394491283010BB8464662F8 }}

      - name: 🚀 Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: 'pdf-expenses-parser'
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
